services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env.frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    restart: always
    env_file:
      - .env.backend
    ports:
      - 5001:5001
