services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env.frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    restart: always
    env_file:
      - .env.backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - 5001:5001
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


    

volumes:
  postgres_data:


