services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    restart: always
    env_file:
      - .env.backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - 80:80



